"""Migration name

Revision ID: d1bab56702ae
Revises: 96036e79307a
Create Date: 2022-06-17 13:26:14.829858

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd1bab56702ae'
down_revision = '96036e79307a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_ip'), 'click', ['ip'], unique=False)
    op.create_table('link',
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numbers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    op.drop_index(op.f('ix_click_ip'), table_name='click')
    op.drop_table('click')
    # ### end Alembic commands ###
